DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(50) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  password VARCHAR(10) NOT NULL,
);